[project]
name = "aip-airspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
gjson = "aip_airspace:cli.aip_to_geojson"

[build-system]
requires = ["uv_build>=0.11.11,<0.12"]
build-backend = "uv_build"
