[project]
name = "aip-airspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "freetype-py>=2.5.1",
    "geopandas>=1.1.3",
    "lxml>=6.1.1",
    "pyproj>=3.7.2",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
]

[project.scripts]
airspace = "aip_airspace:cli.aip_to_geojson"
fixup = "aip_airspace:cli.aip_fixup"
loa = "aip_airspace:cli.loa_to_geojson"
obstacle = "aip_airspace:cli.obstacle_to_geojson"
overlay = "aip_airspace:cli.make_overlay"
rat = "aip_airspace:cli.rat_to_geojson"
sporting = "aip_airspace:cli.sporting_to_geojson"

[build-system]
requires = ["uv_build>=0.11.11,<0.12"]
build-backend = "uv_build"
